import { createContext, useContext, useState, useEffect, ReactNode } from 'react';

interface LanguageContextType {
  language: string;
  setLanguage: (lang: string) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<string, Record<string, string>> = {
  de: {
    // Navigation
    'nav.home': 'Startseite',
    'nav.menu': 'Speisekarte',
    'nav.reservations': 'Reservierungen',
    'nav.contact': 'Kontakt',
    'nav.about': 'Über Uns',
    
    // Hero Section
    'hero.tagline': 'Italian Elegance in Berlin',
    'hero.description': 'Erleben Sie die Kunst der italienischen Küche im Herzen Berlins.',
    'hero.description2': 'Wo Tradition auf Innovation trifft und jedes Gericht eine Geschichte erzählt.',
    'hero.reserve': 'Jetzt Reservieren',
    'hero.viewMenu': 'Speisekarte Ansehen',
    
    // About Section
    'about.title': 'Über Capitolo Rosso',
    'about.p1': 'Willkommen im Capitolo Rosso, wo französische Eleganz auf kulinarische Exzellenz im Herzen Berlins trifft. Unser Restaurant ist eine Feier traditioneller französischer Kochtechniken, erstklassiger Zutaten und raffinierter Gastfreundschaft.',
    'about.p2': 'Seit unserer Gründung widmen wir uns der Aufgabe, unseren Gästen die authentischen Aromen Frankreichs näherzubringen. Jedes Gericht wird mit Leidenschaft zubereitet, unter Verwendung klassischer französischer Rezepte und feinster Zutaten von lokalen Märkten und französischen Lieferanten.',
    'about.p3': 'Unsere talentierten Köche bringen jahrelange Erfahrung aus renommierten französischen Küchen mit und kreieren exquisite Gerichte, die französische kulinarische Traditionen ehren und gleichzeitig moderne Innovationen aufgreifen. Begleiten Sie uns zu einem unvergesslichen kulinarischen Erlebnis.',
    
    // About Page
    'about.hero.title': 'Über Uns',
    'about.hero.subtitle': 'Unsere Geschichte',
    'about.hero.description': 'Von Vino e Libri zu Capitolo Rosso – die Transformation eines beliebten Berliner Standorts in ein authentisches italienisches Restaurant mit italienischen Wurzeln.',
    
    'about.story.title': 'Unsere Geschichte',
    'about.story.subtitle': 'Die Reise',
    'about.story.p1': 'Was einst als Vino e Libri begann – eine charmante Kombination aus Weinbar und Buchhandlung – hat sich zu Capitolo Rosso entwickelt, einem der authentischsten italienischen Restaurants Berlins. Die Transformation war eine Liebesarbeit, die die literarische und kulturelle Essenz des ursprünglichen Raums bewahrte und gleichzeitig die reiche kulinarische Tradition von Italien einbrachte.',
    'about.story.p2': 'Der Name "Capitolo Rosso" (Rotes Kapitel) ehrt sowohl unsere literarischen Wurzeln als auch unsere Verbindung zu den berühmten Rotweinen von Italien. Jedes Gericht, das wir servieren, ist ein neues Kapitel in unserer kulinarischen Geschichte, geschrieben mit den feinsten Zutaten und traditionellen italienischen Techniken.',
    'about.story.p3': 'Heute steht Capitolo Rosso als Zeugnis dafür, wie Tradition und Innovation harmonisch koexistieren können. Wir haben die warme, einladende Atmosphäre bewahrt, die Vino e Libri so beliebt machte, während wir eine kulinarische Erfahrung hinzugefügt haben, die Sie direkt in die Straßen von Rom transportiert.',
    'about.story.quote': 'Jedes Gericht erzählt eine Geschichte, jeder Wein öffnet ein neues Kapitel in Ihrer kulinarischen Reise.',
    
    'about.philosophy.title': 'Unsere Philosophie',
    'about.philosophy.subtitle': 'Was uns antreibt',
    'about.philosophy.quality.title': 'Höchste Qualität',
    'about.philosophy.quality.description': 'Wir verwenden nur die feinsten Zutaten, sorgfältig ausgewählt von vertrauenswürdigen Lieferanten. Jede Zutat wird mit Sorgfalt behandelt, um ihre natürlichen Aromen und Qualität zu bewahren.',
    'about.philosophy.selection.title': 'Sorgfältige Auswahl',
    'about.philosophy.selection.description': 'Unsere Zutaten stammen sowohl von regionalen Berliner Märkten als auch von spezialisierten italienischen Lieferanten, um Authentizität und Frische in jedem Gericht zu gewährleisten.',
    'about.philosophy.ambiance.title': 'Einzigartiges Ambiente',
    'about.philosophy.ambiance.description': 'Jedes Detail unseres Restaurants wurde sorgfältig kuratiert, um eine Atmosphäre zu schaffen, die sowohl elegant als auch einladend ist, perfekt für unvergessliche kulinarische Erlebnisse.',
    
    'about.team.title': 'Unser Team',
    'about.team.subtitle': 'Die Menschen hinter dem Erlebnis',
    'about.team.owner.name': 'Pierre Dubois',
    'about.team.owner.role': 'Inhaber & Gründer',
    'about.team.owner.bio': 'Mit über 25 Jahren Erfahrung in der italienischen Gastronomie bringt Pierre seine Leidenschaft für italienische Weine und italienische Küche nach Berlin.',
    'about.team.chef.name': 'Chef Laurent Moreau',
    'about.team.chef.role': 'Küchenchef',
    'about.team.chef.bio': 'Ausgebildet in Michelin-Sternerestaurants in Rom und Florenz, kreiert Chef Laurent exquisite Gerichte, die italienische Traditionen ehren.',
    'about.team.sommelier.name': 'Sophie Martin',
    'about.team.sommelier.role': 'Sommelière',
    'about.team.sommelier.bio': 'Zertifizierte Sommelière mit Expertise in italienischen Weinen, Sophie kuratiert unsere umfangreiche Weinkarte und führt Sie durch perfekte Paarungen.',
    
    'about.experience.title': 'Das Capitolo Rosso Erlebnis',
    'about.experience.subtitle': 'Was Sie erwartet',
    'about.experience.dining.title': 'Exquisites Essen',
    'about.experience.dining.description': 'Jedes Gericht wird mit Präzision und Leidenschaft zubereitet, unter Verwendung traditioneller italienischer Techniken und der feinsten Zutaten. Von klassischen italienischen Spezialitäten bis hin zu innovativen Kreationen.',
    'about.experience.wine.title': 'Kuratierte Weinauswahl',
    'about.experience.wine.description': 'Unsere umfangreiche Weinkarte zeigt die besten Weine aus der Toskana und ganz Italien. Unsere Sommelière hilft Ihnen gerne, die perfekte Begleitung zu Ihrer Mahlzeit zu finden.',
    'about.experience.ambiance.title': 'Elegantes Ambiente',
    'about.experience.ambiance.description': 'Tauchen Sie ein in eine Atmosphäre, die italienische Eleganz mit Berliner Charme verbindet. Warme Beleuchtung, sorgfältig ausgewähltes Dekor und aufmerksamer Service schaffen das perfekte Ambiente.',
    'about.experience.service.title': 'Aufmerksamer Service',
    'about.experience.service.description': 'Unser engagiertes Team sorgt dafür, dass jeder Aspekt Ihres Besuchs außergewöhnlich ist. Von der Reservierung bis zum letzten Bissen sind wir hier, um Ihr Erlebnis unvergesslich zu machen.',
    
    'about.contact.title': 'Besuchen Sie Uns',
    'about.contact.subtitle': 'Kontakt & Öffnungszeiten',
    'about.contact.address.title': 'Adresse',
    'about.contact.address.line1': 'Capitolo Rosso',
    'about.contact.address.line2': 'Choriner Straße 72, Ecke Zionskirchstraße, 10119 Berlin, Germany',
    'about.contact.phone.title': 'Telefon',
    'about.contact.email.title': 'E-Mail',
    'about.contact.hours.title': 'Öffnungszeiten',
    'about.contact.hours.monday': 'Montag',
    'about.contact.hours.monday.time': 'Geschlossen',
    'about.contact.hours.tuesday': 'Dienstag',
    'about.contact.hours.tuesday.time': '17:00 - 23:00',
    'about.contact.hours.wednesday': 'Mittwoch',
    'about.contact.hours.wednesday.time': '17:00 - 23:00',
    'about.contact.hours.thursday': 'Donnerstag',
    'about.contact.hours.thursday.time': '17:00 - 23:00',
    'about.contact.hours.friday': 'Freitag',
    'about.contact.hours.friday.time': '17:00 - 00:00',
    'about.contact.hours.saturday': 'Samstag',
    'about.contact.hours.saturday.time': '12:00 - 00:00',
    'about.contact.hours.sunday': 'Sonntag',
    'about.contact.hours.sunday.time': '12:00 - 22:00',
    
    // Contact Page
    'contact.hero.title': 'Kontakt',
    'contact.hero.subtitle': 'Kontaktieren Sie Uns',
    'contact.hero.description': 'Wir freuen uns darauf, von Ihnen zu hören. Kontaktieren Sie uns für Reservierungen, Fragen oder besondere Anfragen.',
    'contact.channels.title': 'Kontaktkanäle',
    'contact.channels.subtitle': 'Wählen Sie Ihre bevorzugte Kontaktmethode',
    'contact.location.title': 'Unsere Lage',
    'contact.location.subtitle': 'Besuchen Sie Uns',
    'contact.directions.title': 'So Erreichen Sie Uns',
    'contact.directions.subtitle': 'Anfahrt & Parken',
    'contact.directions.publicTransport': 'Öffentliche Verkehrsmittel',
    'contact.directions.parking': 'Parkmöglichkeiten',
    'contact.directions.accessibility': 'Barrierefreier Zugang',
    'contact.directions.accessibility.description': 'Unser Restaurant ist vollständig rollstuhlgerecht mit barrierefreiem Eingang, zugänglichen Toiletten und geräumigen Sitzgelegenheiten. Wir sind bestrebt, sicherzustellen, dass alle unsere Gäste ihr kulinarisches Erlebnis komfortabel genießen können. Bitte kontaktieren Sie uns im Voraus, wenn Sie spezielle Zugänglichkeitsanforderungen haben.',
    
    // Menu Page
    'menu.title': 'Unsere Speisekarte',
    'menu.subtitle': 'Italienische Küche',
    'menu.hero.subtitle': 'Unsere Speisekarte',
    'menu.hero.description': 'Entdecken Sie unsere exquisite Auswahl an authentischer italienischer Küche',
    'menu.hero.cta.title': 'Bereit für italienische Exzellenz?',
    'menu.hero.cta.description': 'Reservieren Sie noch heute Ihren Tisch und genießen Sie eine unvergessliche kulinarische Reise',
    'menu.hero.cta.button': 'Reservierung vornehmen',
    'menu.allergenNote': 'Allergene sind in der Spalte „Allergene" mit Buchstaben gekennzeichnet.',
    'menu.allergenLegend': 'Allergen-Legende',
    'menu.allergens': 'Allergene',
    
    // Categories
    'category.suppen': 'Suppen',
    'category.antipasti': 'Antipasti',
    'category.salate': 'Salate',
    'category.pasta': 'Pasta',
    'category.tagliatelle': 'Tagliatelle & Gnocchi',
    'category.pizza': 'Pizza',
    'category.focaccia': 'Focaccia',
    
    // Menu Notes
    'menu.salateNote': 'Alle Salate werden wahlweise mit Hausdressing oder Honig-Senf-Dressing serviert.',
    'menu.pizzaNote': 'Alle Pizzen werden mit Tomatensauce und Mozzarella belegt.',
    
    // Footer
    'footer.description': 'Authentische italienische Küche, zubereitet mit Leidenschaft und Tradition seit unserer Gründung.',
    'footer.quickLinks': 'Schnelllinks',
    'footer.legal': 'Rechtliches',
    'footer.contactInfo': 'Kontaktinformationen',
    'footer.impressum': 'Impressum',
    'footer.privacy': 'Datenschutz',
    'footer.rights': '© 2025 Capitolo Rosso. Alle Rechte vorbehalten.',
    'footer.poweredBy': 'Powered by Readdy',
    
    // Hero Section Additional
    'hero.tagline': 'Italienische Eleganz in Berlin',
    'hero.viewFullMenu': 'Vollständige Speisekarte ansehen',
    'hero.reserveTable': 'Tisch reservieren',
    
    // About Section Additional
    'about.subtitle': 'Italienisches Restaurant',
    
    // Specialties Section
    'specialties.description': 'Entdecken Sie unsere vielfältige Auswahl an authentischen Gerichten, zubereitet mit Leidenschaft und den besten Zutaten',
    
    // Testimonials
    'testimonials.title': 'Testimonials',
    'testimonials.subtitle': 'Was unsere Gäste sagen',
    'testimonials.sophie.text': 'Ein außergewöhnliches kulinarisches Erlebnis! Die Aufmerksamkeit für Details in jedem Gericht ist bemerkenswert. Die Pasta ist handgemacht und perfekt, und die Weinauswahl ist makellos.',
    'testimonials.marco.text': 'Dieses Restaurant fühlt sich wie zu Hause an. Die authentischen italienischen Aromen erinnern mich an das Kochen meiner Großmutter. Das Personal behandelt Sie wie Familie, und die Atmosphäre ist perfekt für jeden Anlass.',
    'testimonials.emma.text': 'Ich habe in Restaurants in ganz Europa gegessen, und dieser Ort sticht hervor. Die Pizza ist die beste, die ich außerhalb von Neapel hatte. Die Atmosphäre ist romantisch und der Service ist hervorragend.',
    'testimonials.role.foodCritic': 'Food-Kritikerin',
    'testimonials.role.regularCustomer': 'Stammgast',
    'testimonials.role.travelBlogger': 'Reisebloggerin',
    
    // CTA Section
    'cta.title': 'Reservieren Sie noch heute Ihren Tisch',
    'cta.description': 'Erleben Sie die feinste italienische Küche in einer eleganten Atmosphäre. Buchen Sie jetzt Ihren Tisch und lassen Sie uns ein unvergessliches kulinarisches Erlebnis für Sie schaffen.',
    'cta.reserve': 'Reservierung vornehmen',
    'cta.contact': 'Kontaktieren Sie uns',
    
    // Restaurant Story (Gallery on Home)
    'story.subtitle': 'Unsere Geschichte',
    'story.title': 'Eine kulinarische Reise durch Italien',
    'story.philosophy': 'Unsere kulinarische Philosophie',
    'story.p1': 'Jedes Gericht, das wir servieren, ist ein Zeugnis unseres Engagements für Exzellenz. Wir beziehen die feinsten Zutaten, ehren bewährte Rezepte und verleihen jeder Kreation Leidenschaft und Kunstfertigkeit. Von unseren holzgefeuerten Pizzen bis zu unserer handgemachten Pasta erzählt jeder Biss eine Geschichte.',
    'story.p2': 'Unsere Köche, ausgebildet im Herzen Italiens, bringen jahrzehntelange Erfahrung und ein unerschütterliches Engagement für kulinarische Perfektion mit. Wir glauben, dass gutes Essen Menschen zusammenbringt und Erinnerungen schafft, die ein Leben lang halten.',
    
    // Navigation Additional
    'nav.gallery': 'Galerie',
    'nav.eventsNews': 'Veranstaltungen & Neuigkeiten',
    'nav.login': 'Anmelden',
    'nav.logout': 'Abmelden',
    'nav.manage': 'Verwalten',
    
    // Login
    'login.welcomeBack': 'Willkommen zurück',
    'login.joinUs': 'Werden Sie Mitglied',
    'login.title': 'Anmelden',
    'login.createAccount': 'Konto erstellen',
    'login.name': 'Name',
    'login.email': 'E-Mail',
    'login.password': 'Passwort',
    'login.enterName': 'Geben Sie Ihren Namen ein',
    'login.enterEmail': 'Geben Sie Ihre E-Mail ein',
    'login.enterPassword': 'Geben Sie Ihr Passwort ein',
    'login.signIn': 'Anmelden',
    'login.orContinue': 'Oder fortfahren mit',
    'login.noAccount': 'Haben Sie noch kein Konto?',
    'login.haveAccount': 'Haben Sie bereits ein Konto?',
    'login.register': 'Registrieren',
    'login.invalidCredentials': 'Ungültige E-Mail oder Passwort',
    'login.emailExists': 'E-Mail existiert bereits',
    'login.googleFailed': 'Google-Anmeldung fehlgeschlagen. Bitte versuchen Sie es erneut.',
    'login.nameRequired': 'Name ist erforderlich',
    
    // Events & News
    'events.hero.title': 'Veranstaltungen & Neuigkeiten',
    'events.hero.subtitle': 'Erleben Sie Unvergessliche Momente',
    'events.hero.description': 'Entdecken Sie unsere exklusiven Weinverkostungen, saisonale Menüs und besondere Veranstaltungen.',
    'events.occurring': 'Laufende Veranstaltungen',
    'events.upcoming': 'Bevorstehende Veranstaltungen',
    'events.past': 'Vergangene Veranstaltungen',
    'events.noEvents': 'Keine Veranstaltungen verfügbar',
    'events.readMore': 'Mehr lesen',
    'events.readLess': 'Weniger anzeigen',
    'events.edit': 'Bearbeiten',
    'events.delete': 'Löschen',
    'events.deleteConfirm': 'Möchten Sie diese Veranstaltung wirklich löschen?',
    'events.deleteConfirmText': 'Diese Aktion kann nicht rückgängig gemacht werden.',
    'events.cancel': 'Abbrechen',
    'events.confirm': 'Bestätigen',
    'events.editTitle': 'Veranstaltung bearbeiten',
    'events.title': 'Titel',
    'events.description': 'Beschreibung',
    'events.date': 'Datum',
    'events.time': 'Uhrzeit',
    'events.save': 'Speichern',
    'events.close': 'Schließen',
    'events.services.wineEvents.title': 'Weinabende & Sonderaktionen',
    'events.services.wineEvents.description': 'Regelmäßige Ankündigungen von besonderen Veranstaltungen wie toskanischen Weinverkostungen, Sommelier-Abenden und kulinarischen Themenwochen. Erleben Sie seltene Jahrgänge, gepaart mit sorgfältig ausgewählten italienischen Vorspeisen.',
    'events.services.exclusiveOffers.title': 'Exklusive Angebote',
    'events.services.exclusiveOffers.description': 'Informationen zu Degustationsmenüs, Mittagsangeboten und besonderen Arrangements für Stammgäste. Begeben Sie sich auf eine kulinarische Reise mit den sorgfältig gestalteten Erlebnissen unseres Küchenchefs.',
    'events.services.seasonalUpdates.title': 'Saisonale Updates',
    'events.services.seasonalUpdates.description': 'Blog-ähnlicher Bereich für Neuigkeiten zu saisonalen Menüs, neuen Gerichten und besonderen Empfehlungen des Küchenchefs. Bleiben Sie auf dem Laufenden über unsere neuesten kulinarischen Kreationen.',
    'events.currentEvents': 'Aktuelle Veranstaltungen',
    'events.deleteConfirmMessage': 'Sind Sie sicher, dass Sie',
    'events.static.event1.description': 'Begleiten Sie unseren Sommelier auf eine exklusive Reise durch die feinsten toskanischen Weine. Erleben Sie seltene Jahrgänge, gepaart mit sorgfältig ausgewählten italienischen Vorspeisen in intimer Atmosphäre.',
    'events.static.event2.description': 'Entdecken Sie die Kunst des italienischen Weinbaus mit unserem Experten-Sommelier. Von der Toskana bis zum Piemont erkunden Sie regionale Schätze, gepaart mit authentischer italienischer Küche.',
    'events.static.event3.description': 'Genießen Sie eine Woche, die dem König der Zutaten gewidmet ist. Unser Küchenchef präsentiert exklusive Trüffel-Gerichte, gepaart mit außergewöhnlichen Weinen aus unserem Keller.',
    'events.static.event4.description': 'Unser neues Frühlingsmenü feiert die Saison mit frischem Spargel, wilden Kräutern und zartem Lamm. Die Empfehlungen des Küchenchefs umfassen Risotto Primavera und Pfannengebratenen Seebarsch mit Frühlingsgemüse.',
    'events.static.event5.description': 'Wir präsentieren die neueste Kreation unseres Küchenchefs: Osso Buco alla Milanese mit Safranrisotto und Gremolata. Eine moderne Interpretation eines zeitlosen Klassikers, für begrenzte Zeit erhältlich.',
    
    // Gallery
    'gallery.hero.title': 'Galerie',
    'gallery.hero.subtitle': 'Unsere Atmosphäre',
    'gallery.hero.description': 'Tauchen Sie ein in die elegante Welt des Capitolo Rosso.',
    'gallery.interior.title': 'Interieur & Ambiente',
    'gallery.interior.description': 'Gold- und Holzdetails, die eine warme, edle Atmosphäre schaffen',
    'gallery.culinary.title': 'Kulinarische Kreationen',
    'gallery.culinary.description': 'Künstlerische Präsentation unserer Signature-Gerichte',
    'gallery.moments.title': 'Besondere Momente',
    'gallery.moments.description': 'Veranstaltungen und unvergessliche Erlebnisse unserer Gäste',
    
    // Manage Page
    'manage.title': 'Verwaltung',
    'manage.addItem': 'Menüpunkt hinzufügen',
    'manage.addEvent': 'Veranstaltung hinzufügen',
    'manage.tabItem': 'Menüpunkt',
    'manage.tabEvent': 'Veranstaltung',
    'manage.itemName': 'Name (DE)',
    'manage.itemNameEn': 'Name (EN)',
    'manage.itemDescription': 'Beschreibung (DE)',
    'manage.itemDescriptionEn': 'Beschreibung (EN)',
    'manage.itemAllergens': 'Allergene',
    'manage.itemPrice': 'Preis',
    'manage.itemCategory': 'Kategorie',
    'manage.eventTitle': 'Titel',
    'manage.eventDescription': 'Beschreibung',
    'manage.eventDate': 'Datum',
    'manage.eventTime': 'Uhrzeit',
    'manage.add': 'Hinzufügen',
    'manage.update': 'Aktualisieren',
    'manage.cancel': 'Abbrechen',
    'manage.editItem': 'Menüpunkt bearbeiten',
    'manage.editEvent': 'Veranstaltung bearbeiten',
    'manage.deleteItem': 'Menüpunkt löschen',
    'manage.deleteEvent': 'Veranstaltung löschen',
    'manage.deleteConfirm': 'Möchten Sie dies wirklich löschen?',
    'manage.deleteConfirmText': 'Diese Aktion kann nicht rückgängig gemacht werden.',
    'manage.confirm': 'Bestätigen',
    'manage.success': 'Erfolgreich gespeichert',
    'manage.error': 'Fehler beim Speichern',
    
    // Reservations Page
    'reservations.hero.subtitle': 'Reservierungen',
    'reservations.hero.title': 'Reservieren Sie Ihren Tisch',
    'reservations.hero.description': 'Erleben Sie die feinste italienische Küche in einer Atmosphäre zeitloser Eleganz. Buchen Sie Ihren Tisch und lassen Sie uns eine unvergessliche kulinarische Reise für Sie schaffen.',
    'reservations.booking.title': 'Buchen Sie Ihren Tisch',
    'reservations.booking.subtitle': 'Sichern Sie Ihre Reservierung in nur wenigen Klicks',
    'reservations.booking.button': 'Jetzt Tisch buchen',
    'reservations.occasions.title': 'Besondere Anlässe',
    'reservations.occasions.description': 'Schaffen Sie unvergessliche Erinnerungen mit uns. Ob eine intime Feier oder ein großes Event, wir bieten die perfekte Kulisse für Ihre besonderen Momente.',
    'reservations.occasions.private.title': 'Private Feiern',
    'reservations.occasions.private.description': 'Feiern Sie die kostbaren Momente des Lebens in unseren exklusiven privaten Speiseräumen. Perfekt für Geburtstage, Jubiläen und intime Zusammenkünfte mit bis zu 20 Gästen.',
    'reservations.occasions.private.menu': 'Personalisierte Menüplanung mit unserem Küchenchef',
    'reservations.occasions.private.staff': 'Dediziertes Servicepersonal für Ihre Veranstaltung',
    'reservations.occasions.private.decorations': 'Individuelle Dekorationen und Ambiente',
    'reservations.occasions.corporate.title': 'Firmenveranstaltungen',
    'reservations.occasions.corporate.description': 'Beeindrucken Sie Ihre Kunden und Kollegen mit unserem anspruchsvollen Firmen-Dining-Erlebnis. Ideal für Geschäftstreffen, Teamfeiern und Networking-Events.',
    'reservations.occasions.corporate.atmosphere': 'Professionelle Atmosphäre und Service',
    'reservations.occasions.corporate.seating': 'Flexible Sitzanordnungen',
    'reservations.occasions.corporate.equipment': 'Audio-Visuelle Ausstattung verfügbar',
    'reservations.occasions.wedding.title': 'Hochzeitsfeiern',
    'reservations.occasions.wedding.description': 'Machen Sie Ihren besonderen Tag wirklich unvergesslich mit unseren eleganten Hochzeitsfeier-Services. Wir schaffen magische Momente mit exquisiter Küche und makellosem Service.',
    'reservations.occasions.wedding.menus': 'Individuelle Hochzeitsmenüs',
    'reservations.occasions.wedding.decoration': 'Elegante Venue-Dekoration',
    'reservations.occasions.wedding.coordination': 'Professionelle Event-Koordination',
    'reservations.contact.title': 'Kontaktinformationen',
    'reservations.contact.phone.title': 'Telefonnummer',
    'reservations.contact.phone.description': 'Für direkte Anfragen und Reservierungen',
    'reservations.contact.email.title': 'E-Mail-Adresse',
    'reservations.contact.email.description': 'Für besondere Anfragen und Anfragen',
    
    // Impressum
    'impressum.title': 'Impressum',
    'impressum.ddg.title': 'Angaben gemäß § 5 Digitale-Dienste-Gesetz (DDG)',
    'impressum.ddg.owner': 'Inhaber und Verantwortlicher im Sinne des § 18 Abs. 2 Medienstaatsvertrag (MStV):',
    'impressum.ddg.contact': 'Kontaktinformationen:',
    'impressum.ddg.phone': 'Telefon:',
    'impressum.ddg.email': 'E-Mail:',
    'impressum.ddg.internet': 'Internet:',
    'impressum.liability.content.title': 'Haftung für Inhalte',
    'impressum.liability.content.text': 'Als Diensteanbieter sind wir gemäß § 7 Abs. 1 DDG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 DDG sind wir als Diensteanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen. Verpflichtungen zur Entfernung oder Sperrung der Nutzung von Informationen nach den allgemeinen Gesetzen bleiben hiervon unberührt. Eine diesbezügliche Haftung ist jedoch erst ab dem Zeitpunkt der Kenntnis einer konkreten Rechtsverletzung möglich. Bei Bekanntwerden von entsprechenden Rechtsverletzungen werden wir diese Inhalte umgehend entfernen.',
    'impressum.liability.links.title': 'Haftung für Links',
    'impressum.liability.links.text': 'Unser Angebot enthält Links zu externen Websites Dritter, auf deren Inhalte wir keinen Einfluss haben. Deshalb können wir für diese fremden Inhalte auch keine Gewähr übernehmen. Für die Inhalte der verlinkten Seiten ist stets der jeweilige Anbieter oder Betreiber der Seiten verantwortlich. Die verlinkten Seiten wurden zum Zeitpunkt der Verlinkung auf mögliche Rechtsverstöße überprüft. Rechtswidrige Inhalte waren zum Zeitpunkt der Verlinkung nicht erkennbar. Eine permanente inhaltliche Kontrolle der verlinkten Seiten ist jedoch ohne konkrete Anhaltspunkte einer Rechtsverletzung nicht zumutbar. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Links umgehend entfernen.',
    'impressum.copyright.title': 'Urheberrecht',
    'impressum.copyright.text': 'Die durch die Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem deutschen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung außerhalb der Grenzen des Urheberrechts bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet. Soweit die Inhalte auf dieser Seite nicht vom Betreiber erstellt wurden, werden die Urheberrechte Dritter beachtet. Insbesondere werden Inhalte Dritter als solche gekennzeichnet. Sollten Sie trotzdem auf eine Urheberrechtsverletzung aufmerksam werden, bitten wir um einen entsprechenden Hinweis. Bei Bekanntwerden von Rechtsverletzungen werden wir derartige Inhalte umgehend entfernen.',
    'impressum.dispute.title': 'Verbraucherstreitbeilegung / Online-Streitbeilegung',
    'impressum.dispute.text': 'Die Europäische Kommission stellt eine Plattform zur Online-Streitbeilegung (OS) bereit:',
    'impressum.dispute.notice': 'Wir sind nicht verpflichtet und nicht bereit, an einem Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.',
    
    // Privacy Policy
    'privacy.title': 'Datenschutzerklärung',
    'privacy.intro': 'Diese Datenschutzerklärung informiert gemäß Art. 12 ff. DSGVO umfassend über Art, Umfang und Zweck der Verarbeitung personenbezogener Daten einschließlich Social-Media-Präsenzen.',
    'privacy.responsible.title': '1. Verantwortlicher',
    'privacy.responsible.owner': 'Inhaber:',
    'privacy.responsible.phone': 'Telefon:',
    'privacy.responsible.email': 'E-Mail:',
    'privacy.responsible.website': 'Website:',
    'privacy.social.title': '2. Social-Media-Präsenzen',
    'privacy.social.text': 'Wir unterhalten öffentlich zugängliche Profile in sozialen Netzwerken, um mit Gästen und Interessenten zu kommunizieren sowie unser Angebot zu präsentieren. Beim Besuch unserer Social-Media-Seiten werden personenbezogene Daten durch die jeweiligen Plattformbetreiber verarbeitet. Dabei kann es zu einer Verarbeitung außerhalb der Europäischen Union kommen.',
    'privacy.social.legal': 'Rechtsgrundlage:',
    'privacy.social.legal.text': 'Art. 6 Abs. 1 lit. f DSGVO (berechtigtes Interesse an Öffentlichkeitsarbeit und Kommunikation).',
    'privacy.instagram.title': '3. Instagram',
    'privacy.instagram.text': 'Auf unserer Website können Funktionen und Inhalte des Dienstes Instagram eingebunden sein oder es bestehen Verlinkungen zu unserem Instagram-Profil. Anbieter: Meta Platforms Ireland Ltd., 4 Grand Canal Square, Dublin 2, Irland. Bei Nutzung von Instagram werden personenbezogene Daten auch in die USA übermittelt. Die Datenübermittlung erfolgt auf Grundlage von Standardvertragsklauseln der EU-Kommission. Weitere Informationen finden Sie in der Datenschutzerklärung von Instagram.',
    'privacy.facebook.title': '4. Facebook',
    'privacy.facebook.text': 'Wir betreiben eine Facebook-Seite. Anbieter: Meta Platforms Ireland Ltd., 4 Grand Canal Square, Dublin 2, Irland. Beim Besuch unserer Facebook-Seite verarbeitet Meta personenbezogene Daten eigenverantwortlich.',
    'privacy.google.title': '5. Google Unternehmensprofil',
    'privacy.google.text': 'Wir nutzen ein Google Unternehmensprofil zur Darstellung unseres Restaurants. Anbieter: Google Ireland Limited, Dublin, Irland. Dabei kann Google Nutzungsdaten erfassen.',
    'privacy.embedding.title': '6. Einbindung von Social-Media-Inhalten',
    'privacy.embedding.text': 'Sofern Social-Media-Inhalte (z. B. Instagram-Feeds) direkt auf unserer Website eingebunden sind, erfolgt dies ausschließlich nach Ihrer vorherigen Einwilligung über das Cookie-Consent-Banner.',
    'privacy.embedding.legal': 'Rechtsgrundlage:',
    'privacy.embedding.legal.text': 'Art. 6 Abs. 1 lit. a DSGVO.',
    'privacy.rights.title': '7. Ihre Rechte',
    'privacy.rights.intro': 'Sie haben folgende Rechte:',
    'privacy.rights.info': 'Auskunft (Art. 15 DSGVO)',
    'privacy.rights.correction': 'Berichtigung (Art. 16 DSGVO)',
    'privacy.rights.deletion': 'Löschung (Art. 17 DSGVO)',
    'privacy.rights.restriction': 'Einschränkung (Art. 18 DSGVO)',
    'privacy.rights.objection': 'Widerspruch (Art. 21 DSGVO)',
    'privacy.rights.complaint': 'Beschwerde bei einer Aufsichtsbehörde',
    'privacy.current.title': '8. Aktualität',
    'privacy.current.text': 'Diese Datenschutzerklärung ist aktuell gültig (Stand: January 2026).'
  },
  en: {
    // Navigation
    'nav.home': 'Home',
    'nav.menu': 'Menu',
    'nav.reservations': 'Reservations',
    'nav.contact': 'Contact',
    'nav.about': 'About Us',
    
    // Hero Section
    'hero.tagline': 'Italian Elegance in Berlin',
    'hero.description': 'Experience the art of Italian cuisine in the heart of Berlin.',
    'hero.description2': 'Where tradition meets innovation, and every dish tells a story.',
    'hero.reserve': 'Reserve Now',
    'hero.viewMenu': 'View Menu',
    
    // About Section
    'about.title': 'About Capitolo Rosso',
    'about.p1': 'Welcome to Capitolo Rosso, where Italian elegance meets culinary excellence in the heart of Berlin. Our restaurant is a celebration of traditional Italian cooking techniques, premium ingredients, and refined hospitality.',
    'about.p2': 'Since our founding, we have been dedicated to bringing the authentic flavors of Italy to our guests. Every dish is crafted with passion, using classic Italian recipes and the finest ingredients sourced from local markets and Italian suppliers.',
    'about.p3': 'Our talented chefs bring years of experience from renowned Italian kitchens, creating exquisite dishes that honor Italian culinary traditions while embracing modern innovation. Join us for an unforgettable dining experience.',
    
    // About Page
    'about.hero.title': 'About Us',
    'about.hero.subtitle': 'Our Story',
    'about.hero.description': 'From Vino e Libri to Capitolo Rosso – the transformation of a beloved Berlin location into an authentic Italian restaurant with Italian roots.',
    
    'about.story.title': 'Our Story',
    'about.story.subtitle': 'The Journey',
    'about.story.p1': 'What began as Vino e Libri – a charming combination of wine bar and bookstore – has evolved into Capitolo Rosso, one of Berlin\'s most authentic Italian restaurants. The transformation was a labor of love, preserving the literary and cultural essence of the original space while infusing it with the rich culinary tradition of Italy.',
    'about.story.p2': 'The name "Capitolo Rosso" (Red Chapter) honors both our literary roots and our connection to the famous red wines of Italy. Each dish we serve is a new chapter in our culinary story, written with the finest ingredients and traditional Italian techniques.',
    'about.story.p3': 'Today, Capitolo Rosso stands as a testament to how tradition and innovation can coexist harmoniously. We\'ve maintained the warm, welcoming atmosphere that made Vino e Libri so beloved, while adding a culinary experience that transports you to the streets of Rome.',
    'about.story.quote': 'Every dish tells a story, every wine opens a new chapter in your culinary journey.',
    
    'about.philosophy.title': 'Our Philosophy',
    'about.philosophy.subtitle': 'What Drives Us',
    'about.philosophy.quality.title': 'Highest Quality',
    'about.philosophy.quality.description': 'We use only the finest ingredients, carefully selected from trusted suppliers. Each ingredient is treated with care to preserve its natural flavors and quality.',
    'about.philosophy.selection.title': 'Careful Selection',
    'about.philosophy.selection.description': 'Our ingredients are sourced from both regional Berlin markets and specialized Italian suppliers, ensuring authenticity and freshness in every dish.',
    'about.philosophy.ambiance.title': 'Unique Ambiance',
    'about.philosophy.ambiance.description': 'Every detail of our restaurant has been carefully curated to create an atmosphere that is both elegant and welcoming, perfect for memorable dining experiences.',
    
    'about.team.title': 'Our Team',
    'about.team.subtitle': 'The People Behind the Experience',
    'about.team.owner.name': 'Pierre Dubois',
    'about.team.owner.role': 'Owner & Founder',
    'about.team.owner.bio': 'With over 25 years of experience in Italian hospitality, Pierre brings his passion for Italian wines and Italian cuisine to Berlin.',
    'about.team.chef.name': 'Chef Laurent Moreau',
    'about.team.chef.role': 'Head Chef',
    'about.team.chef.bio': 'Trained in Michelin-starred restaurants in Rome and Florence, Chef Laurent creates exquisite dishes that honor Italian traditions.',
    'about.team.sommelier.name': 'Sophie Martin',
    'about.team.sommelier.role': 'Sommelier',
    'about.team.sommelier.bio': 'Certified sommelier with expertise in Italian wines, Sophie curates our extensive wine list and guides you through perfect pairings.',
    
    'about.experience.title': 'The Capitolo Rosso Experience',
    'about.experience.subtitle': 'What to Expect',
    'about.experience.dining.title': 'Exquisite Dining',
    'about.experience.dining.description': 'Each dish is prepared with precision and passion, using traditional Italian techniques and the finest ingredients. From classic Italian specialties to innovative creations.',
    'about.experience.wine.title': 'Curated Wine Selection',
    'about.experience.wine.description': 'Our extensive wine list showcases the best wines from Tuscany and across Italy. Our sommelier is happy to help you find the perfect pairing for your meal.',
    'about.experience.ambiance.title': 'Elegant Ambiance',
    'about.experience.ambiance.description': 'Immerse yourself in an atmosphere that blends Italian elegance with Berlin charm. Warm lighting, carefully selected decor, and attentive service create the perfect setting.',
    'about.experience.service.title': 'Attentive Service',
    'about.experience.service.description': 'Our dedicated team ensures that every aspect of your visit is exceptional. From reservation to the last bite, we\'re here to make your experience memorable.',
    
    'about.contact.title': 'Visit Us',
    'about.contact.subtitle': 'Contact & Hours',
    'about.contact.address.title': 'Address',
    'about.contact.address.line1': 'Capitolo Rosso',
    'about.contact.address.line2': 'Choriner Straße 72, Ecke Zionskirchstraße, 10119 Berlin, Germany',
    'about.contact.phone.title': 'Phone',
    'about.contact.email.title': 'Email',
    'about.contact.hours.title': 'Opening Hours',
    'about.contact.hours.monday': 'Monday',
    'about.contact.hours.monday.time': 'Closed',
    'about.contact.hours.tuesday': 'Tuesday',
    'about.contact.hours.tuesday.time': '5:00 PM - 11:00 PM',
    'about.contact.hours.wednesday': 'Wednesday',
    'about.contact.hours.wednesday.time': '5:00 PM - 11:00 PM',
    'about.contact.hours.thursday': 'Thursday',
    'about.contact.hours.thursday.time': '5:00 PM - 11:00 PM',
    'about.contact.hours.friday': 'Friday',
    'about.contact.hours.friday.time': '5:00 PM - 12:00 AM',
    'about.contact.hours.saturday': 'Saturday',
    'about.contact.hours.saturday.time': '12:00 PM - 12:00 AM',
    'about.contact.hours.sunday': 'Sunday',
    'about.contact.hours.sunday.time': '12:00 PM - 10:00 PM',
    
    // Contact Page
    'contact.hero.title': 'Contact',
    'contact.hero.subtitle': 'Contact Us',
    'contact.hero.description': 'We\'d love to hear from you. Reach out for reservations, questions, or special requests.',
    'contact.channels.title': 'Contact Channels',
    'contact.channels.subtitle': 'Choose Your Preferred Way to Reach Us',
    'contact.location.title': 'Our Location',
    'contact.location.subtitle': 'Visit Us',
    'contact.directions.title': 'How to Reach Us',
    'contact.directions.subtitle': 'Directions & Parking',
    'contact.directions.publicTransport': 'Public Transport',
    'contact.directions.parking': 'Parking',
    'contact.directions.accessibility': 'Barrier-Free Access',
    'contact.directions.accessibility.description': 'Our restaurant is fully wheelchair accessible with a barrier-free entrance, accessible restrooms, and spacious seating arrangements. We are committed to ensuring all our guests can enjoy their dining experience comfortably. Please contact us in advance if you have specific accessibility requirements.',
    
    // Menu Page
    'menu.title': 'Our Menu',
    'menu.subtitle': 'Italian Cuisine',
    'menu.hero.subtitle': 'Our Menu',
    'menu.hero.description': 'Explore our exquisite selection of authentic Italian cuisine',
    'menu.hero.cta.title': 'Ready to Experience Italian Excellence?',
    'menu.hero.cta.description': 'Reserve your table today and indulge in an unforgettable culinary journey',
    'menu.hero.cta.button': 'Make a Reservation',
    'menu.allergenNote': 'Allergens are marked with letters in the "Allergens" column.',
    'menu.allergenLegend': 'Allergen Legend',
    'menu.allergens': 'Allergens',
    
    // Categories
    'category.suppen': 'Soups',
    'category.antipasti': 'Antipasti',
    'category.salate': 'Salads',
    'category.pasta': 'Pasta',
    'category.tagliatelle': 'Tagliatelle & Gnocchi',
    'category.pizza': 'Pizza',
    'category.focaccia': 'Focaccia',
    
    // Menu Notes
    'menu.salateNote': 'All salads are served with your choice of house dressing or honey-mustard dressing.',
    'menu.pizzaNote': 'All pizzas are topped with tomato sauce and mozzarella.',
    
    // Footer
    'footer.description': 'Authentic Italian cuisine crafted with passion and tradition since our founding.',
    'footer.quickLinks': 'Quick Links',
    'footer.legal': 'Legal',
    'footer.contactInfo': 'Contact Info',
    'footer.impressum': 'Imprint',
    'footer.privacy': 'Privacy Policy',
    'footer.rights': '© 2025 Capitolo Rosso. All rights reserved.',
    'footer.poweredBy': 'Powered by Readdy',
    
    // Hero Section Additional
    'hero.tagline': 'Italian Elegance in Berlin',
    'hero.viewFullMenu': 'View Full Menu',
    'hero.reserveTable': 'Reserve Table',
    
    // About Section Additional
    'about.subtitle': 'Italian Restaurant',
    
    // Specialties Section
    'specialties.description': 'Discover our diverse selection of authentic dishes, prepared with passion and the finest ingredients',
    
    // Testimonials
    'testimonials.title': 'Testimonials',
    'testimonials.subtitle': 'What Our Guests Say',
    'testimonials.sophie.text': 'An extraordinary culinary experience! The attention to detail in every dish is remarkable. The pasta is handmade to perfection, and the wine selection is impeccable.',
    'testimonials.marco.text': 'This restaurant feels like home. The authentic Italian flavors remind me of my grandmother\'s cooking. The staff treats you like family, and the ambiance is perfect for any occasion.',
    'testimonials.emma.text': 'I\'ve dined at restaurants across Europe, and this place stands out. The pizza is the best I\'ve had outside of Naples. The atmosphere is romantic and the service is outstanding.',
    'testimonials.role.foodCritic': 'Food Critic',
    'testimonials.role.regularCustomer': 'Regular Customer',
    'testimonials.role.travelBlogger': 'Travel Blogger',
    
    // CTA Section
    'cta.title': 'Reserve Your Table Today',
    'cta.description': 'Experience the finest Italian cuisine in an elegant atmosphere. Book your table now and let us create an unforgettable dining experience for you.',
    'cta.reserve': 'Make a Reservation',
    'cta.contact': 'Contact Us',
    
    // Restaurant Story (Gallery on Home)
    'story.subtitle': 'Our Story',
    'story.title': 'A Culinary Journey Through Italy',
    'story.philosophy': 'Our Culinary Philosophy',
    'story.p1': 'Every dish we serve is a testament to our commitment to excellence. We source the finest ingredients, honor time-tested recipes, and infuse each creation with passion and artistry. From our wood-fired pizzas to our handcrafted pasta, every bite tells a story.',
    'story.p2': 'Our chefs, trained in the heart of Italy, bring decades of experience and an unwavering dedication to culinary perfection. We believe that great food brings people together, creating memories that last a lifetime.',
    
    // Navigation Additional
    'nav.gallery': 'Gallery',
    'nav.eventsNews': 'Events & News',
    'nav.login': 'Login',
    'nav.logout': 'Logout',
    'nav.manage': 'Manage',
    
    // Login
    'login.welcomeBack': 'Welcome Back',
    'login.joinUs': 'Join Us',
    'login.title': 'Login',
    'login.createAccount': 'Create Account',
    'login.name': 'Name',
    'login.email': 'Email',
    'login.password': 'Password',
    'login.enterName': 'Enter your name',
    'login.enterEmail': 'Enter your email',
    'login.enterPassword': 'Enter your password',
    'login.signIn': 'Sign In',
    'login.orContinue': 'Or continue with',
    'login.noAccount': 'Don\'t have an account?',
    'login.haveAccount': 'Already have an account?',
    'login.register': 'Register',
    'login.invalidCredentials': 'Invalid email or password',
    'login.emailExists': 'Email already exists',
    'login.googleFailed': 'Google sign-in failed. Please try again.',
    'login.nameRequired': 'Name is required',
    
    // Events & News
    'events.hero.title': 'Events & News',
    'events.hero.subtitle': 'Experience Unforgettable Moments',
    'events.hero.description': 'Discover our exclusive wine tastings, seasonal menus, and special events.',
    'events.occurring': 'Occurring Events',
    'events.upcoming': 'Upcoming Events',
    'events.past': 'Past Events',
    'events.noEvents': 'No events available',
    'events.readMore': 'Read More',
    'events.readLess': 'Show Less',
    'events.edit': 'Edit',
    'events.delete': 'Delete',
    'events.deleteConfirm': 'Are you sure you want to delete this event?',
    'events.deleteConfirmText': 'This action cannot be undone.',
    'events.cancel': 'Cancel',
    'events.confirm': 'Confirm',
    'events.editTitle': 'Edit Event',
    'events.title': 'Title',
    'events.description': 'Description',
    'events.date': 'Date',
    'events.time': 'Time',
    'events.save': 'Save',
    'events.close': 'Close',
    'events.services.wineEvents.title': 'Wine Evenings & Special Promotions',
    'events.services.wineEvents.description': 'Regular announcements of special events like Tuscan wine tastings, sommelier evenings, and culinary themed weeks. Experience rare vintages paired with carefully selected Italian appetizers.',
    'events.services.exclusiveOffers.title': 'Exclusive Offers',
    'events.services.exclusiveOffers.description': 'Information on tasting menus, lunch specials, and special arrangements for regular guests. Embark on a culinary journey with our chef\'s carefully crafted experiences.',
    'events.services.seasonalUpdates.title': 'Seasonal Updates',
    'events.services.seasonalUpdates.description': 'Blog-like section for news on seasonal menus, new dishes, and special recommendations from the chef. Stay updated with our latest culinary creations.',
    'events.currentEvents': 'Current Events',
    'events.deleteConfirmMessage': 'Are you sure you want to delete',
    'events.static.event1.description': 'Join our sommelier for an exclusive journey through the finest Tuscan wines. Experience rare vintages paired with carefully selected Italian appetizers in an intimate setting.',
    'events.static.event2.description': 'Discover the art of Italian winemaking with our expert sommelier. From Tuscany to Piedmont, explore regional treasures paired with authentic Italian cuisine.',
    'events.static.event3.description': 'Indulge in a week dedicated to the king of ingredients. Our chef presents exclusive truffle-infused dishes paired with exceptional wines from our cellar.',
    'events.static.event4.description': 'Our new spring menu celebrates the season with fresh asparagus, wild herbs, and tender lamb. Chef\'s recommendations include Risotto Primavera and Pan-Seared Sea Bass with spring vegetables.',
    'events.static.event5.description': 'Introducing our chef\'s latest creation: Osso Buco alla Milanese with saffron risotto and gremolata. A modern interpretation of a timeless classic, available for a limited time.',
    
    // Gallery
    'gallery.hero.title': 'Gallery',
    'gallery.hero.subtitle': 'Our Atmosphere',
    'gallery.hero.description': 'Immerse yourself in the elegant world of Capitolo Rosso.',
    'gallery.interior.title': 'Interior & Ambiance',
    'gallery.interior.description': 'Gold and wood details that create a warm, noble atmosphere',
    'gallery.culinary.title': 'Culinary Creations',
    'gallery.culinary.description': 'Artistic presentation of our signature dishes',
    'gallery.moments.title': 'Special Moments',
    'gallery.moments.description': 'Events and unforgettable experiences of our guests',
    
    // Manage Page
    'manage.title': 'Management',
    'manage.addItem': 'Add Menu Item',
    'manage.addEvent': 'Add Event',
    'manage.tabItem': 'Menu Item',
    'manage.tabEvent': 'Event',
    'manage.itemName': 'Name (DE)',
    'manage.itemNameEn': 'Name (EN)',
    'manage.itemDescription': 'Description (DE)',
    'manage.itemDescriptionEn': 'Description (EN)',
    'manage.itemAllergens': 'Allergens',
    'manage.itemPrice': 'Price',
    'manage.itemCategory': 'Category',
    'manage.eventTitle': 'Title',
    'manage.eventDescription': 'Description',
    'manage.eventDate': 'Date',
    'manage.eventTime': 'Time',
    'manage.add': 'Add',
    'manage.update': 'Update',
    'manage.cancel': 'Cancel',
    'manage.editItem': 'Edit Menu Item',
    'manage.editEvent': 'Edit Event',
    'manage.deleteItem': 'Delete Menu Item',
    'manage.deleteEvent': 'Delete Event',
    'manage.deleteConfirm': 'Are you sure you want to delete this?',
    'manage.deleteConfirmText': 'This action cannot be undone.',
    'manage.confirm': 'Confirm',
    'manage.success': 'Successfully saved',
    'manage.error': 'Error saving',
    
    // Reservations Page
    'reservations.hero.subtitle': 'Reservations',
    'reservations.hero.title': 'Reserve Your Table',
    'reservations.hero.description': 'Experience the finest Italian cuisine in an atmosphere of timeless elegance. Book your table and let us create an unforgettable culinary journey for you.',
    'reservations.booking.title': 'Book Your Table',
    'reservations.booking.subtitle': 'Secure your reservation in just a few clicks',
    'reservations.booking.button': 'Book Your Table Now',
    'reservations.occasions.title': 'Special Occasions',
    'reservations.occasions.description': 'Create unforgettable memories with us. Whether it\'s an intimate celebration or a grand event, we provide the perfect setting for your special moments.',
    'reservations.occasions.private.title': 'Private Celebrations',
    'reservations.occasions.private.description': 'Celebrate life\'s precious moments in our exclusive private dining rooms. Perfect for birthdays, anniversaries, and intimate gatherings of up to 20 guests.',
    'reservations.occasions.private.menu': 'Personalized menu planning with our chef',
    'reservations.occasions.private.staff': 'Dedicated service staff for your event',
    'reservations.occasions.private.decorations': 'Custom decorations and ambiance',
    'reservations.occasions.corporate.title': 'Corporate Events',
    'reservations.occasions.corporate.description': 'Impress your clients and colleagues with our sophisticated corporate dining experience. Ideal for business meetings, team celebrations, and networking events.',
    'reservations.occasions.corporate.atmosphere': 'Professional atmosphere and service',
    'reservations.occasions.corporate.seating': 'Flexible seating arrangements',
    'reservations.occasions.corporate.equipment': 'Audio-visual equipment available',
    'reservations.occasions.wedding.title': 'Wedding Receptions',
    'reservations.occasions.wedding.description': 'Make your special day truly unforgettable with our elegant wedding reception services. We create magical moments with exquisite cuisine and impeccable service.',
    'reservations.occasions.wedding.menus': 'Customized wedding menus',
    'reservations.occasions.wedding.decoration': 'Elegant venue decoration',
    'reservations.occasions.wedding.coordination': 'Professional event coordination',
    'reservations.contact.title': 'Contact Information',
    'reservations.contact.phone.title': 'Phone Number',
    'reservations.contact.phone.description': 'For direct inquiries and reservations',
    'reservations.contact.email.title': 'Email Address',
    'reservations.contact.email.description': 'For special requests and inquiries',
    
    // Impressum
    'impressum.title': 'Imprint',
    'impressum.ddg.title': 'Information according to § 5 Digital Services Act (DSA)',
    'impressum.ddg.owner': 'Owner and responsible party according to § 18 para. 2 Media State Treaty (MStV):',
    'impressum.ddg.contact': 'Contact Information:',
    'impressum.ddg.phone': 'Phone:',
    'impressum.ddg.email': 'Email:',
    'impressum.ddg.internet': 'Internet:',
    'impressum.liability.content.title': 'Liability for Content',
    'impressum.liability.content.text': 'As a service provider, we are responsible for our own content on these pages according to § 7 para. 1 DSA and general laws. However, according to §§ 8 to 10 DSA, we as a service provider are not obligated to monitor transmitted or stored third-party information or to investigate circumstances that indicate illegal activity. Obligations to remove or block the use of information under general laws remain unaffected. However, liability in this regard is only possible from the point in time of knowledge of a specific legal violation. Upon becoming aware of corresponding legal violations, we will remove this content immediately.',
    'impressum.liability.links.title': 'Liability for Links',
    'impressum.liability.links.text': 'Our offer contains links to external websites of third parties, on whose content we have no influence. Therefore, we cannot assume any guarantee for these external contents. The respective provider or operator of the pages is always responsible for the content of the linked pages. The linked pages were checked for possible legal violations at the time of linking. Illegal content was not recognizable at the time of linking. However, a permanent content control of the linked pages is not reasonable without concrete evidence of a legal violation. Upon becoming aware of legal violations, we will remove such links immediately.',
    'impressum.copyright.title': 'Copyright',
    'impressum.copyright.text': 'The content and works created by the site operators on these pages are subject to German copyright law. The duplication, processing, distribution and any kind of exploitation outside the limits of copyright require the written consent of the respective author or creator. Downloads and copies of this page are only permitted for private, non-commercial use. Insofar as the content on this page was not created by the operator, the copyrights of third parties are observed. In particular, third-party content is identified as such. Should you nevertheless become aware of a copyright infringement, please inform us accordingly. Upon becoming aware of legal violations, we will remove such content immediately.',
    'impressum.dispute.title': 'Consumer Dispute Resolution / Online Dispute Resolution',
    'impressum.dispute.text': 'The European Commission provides a platform for online dispute resolution (OS):',
    'impressum.dispute.notice': 'We are not obligated and not willing to participate in a dispute resolution procedure before a consumer arbitration board.',
    
    // Privacy Policy
    'privacy.title': 'Privacy Policy',
    'privacy.intro': 'This privacy policy informs comprehensively in accordance with Art. 12 ff. GDPR about the type, scope and purpose of the processing of personal data including social media presences.',
    'privacy.responsible.title': '1. Responsible Party',
    'privacy.responsible.owner': 'Owner:',
    'privacy.responsible.phone': 'Phone:',
    'privacy.responsible.email': 'Email:',
    'privacy.responsible.website': 'Website:',
    'privacy.social.title': '2. Social Media Presences',
    'privacy.social.text': 'We maintain publicly accessible profiles in social networks in order to communicate with guests and interested parties as well as to present our offer. When visiting our social media pages, personal data is processed by the respective platform operators. This may result in processing outside the European Union.',
    'privacy.social.legal': 'Legal Basis:',
    'privacy.social.legal.text': 'Art. 6 para. 1 lit. f GDPR (legitimate interest in public relations and communication).',
    'privacy.instagram.title': '3. Instagram',
    'privacy.instagram.text': 'Our website may include functions and content from the Instagram service or there may be links to our Instagram profile. Provider: Meta Platforms Ireland Ltd., 4 Grand Canal Square, Dublin 2, Ireland. When using Instagram, personal data may also be transmitted to the USA. The data transmission is based on standard contractual clauses of the EU Commission. Further information can be found in Instagram\'s privacy policy.',
    'privacy.facebook.title': '4. Facebook',
    'privacy.facebook.text': 'We operate a Facebook page. Provider: Meta Platforms Ireland Ltd., 4 Grand Canal Square, Dublin 2, Ireland. When visiting our Facebook page, Meta processes personal data on its own responsibility.',
    'privacy.google.title': '5. Google Business Profile',
    'privacy.google.text': 'We use a Google Business Profile to display our restaurant. Provider: Google Ireland Limited, Dublin, Ireland. Google may collect usage data.',
    'privacy.embedding.title': '6. Integration of Social Media Content',
    'privacy.embedding.text': 'If social media content (e.g., Instagram feeds) is directly embedded on our website, this is done exclusively after your prior consent via the cookie consent banner.',
    'privacy.embedding.legal': 'Legal Basis:',
    'privacy.embedding.legal.text': 'Art. 6 para. 1 lit. a GDPR.',
    'privacy.rights.title': '7. Your Rights',
    'privacy.rights.intro': 'You have the following rights:',
    'privacy.rights.info': 'Right of access (Art. 15 GDPR)',
    'privacy.rights.correction': 'Right to rectification (Art. 16 GDPR)',
    'privacy.rights.deletion': 'Right to erasure (Art. 17 GDPR)',
    'privacy.rights.restriction': 'Right to restriction (Art. 18 GDPR)',
    'privacy.rights.objection': 'Right to object (Art. 21 GDPR)',
    'privacy.rights.complaint': 'Right to lodge a complaint with a supervisory authority',
    'privacy.current.title': '8. Currency',
    'privacy.current.text': 'This privacy policy is currently valid (as of: January 2026).'
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<string>('de');

  useEffect(() => {
    const savedLanguage = localStorage.getItem('language') || 'de';
    setLanguageState(savedLanguage);
  }, []);

  const setLanguage = (lang: string) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
  };

  const t = (key: string): string => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}